### ISSUE TITLE
Update reflecting msal4j v. 1.4.0

### ISSUE THREAD

**Issue by baardl** [idun-corp/Idun-Examples#4]
`clientId, ClientCredentialFactory.create(clientSecret))` -> `clientId, ClientCredentialFactory.createFromSecret(clientSecret))` in https://github.com/Vasakronan/Idun-Examples/blob/master/ProptechOS-Api/authentication/examples/java/AppTokenRetrieval.java

**Comment by marichka-spin** [comment]
The example code was updated according to new version of msal library
